signal_path: /scratch/r/rbond/msyriac/data/sims/alex/v0.4/
data_path: /home/r/rbond/jiaqu/scratch/so_lens
output_path: /home/r/rbond/jiaqu/scratch/so_lens
mask_name: simonsobs_noise_mask_x_mask_V3_bool.fits
theory_root: cosmo2017_10K_acc3
